Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_url = "ubuntu/trusty64"

    config.vm.synced_folder "../Code", "/home/vagrant/code"
    config.vm.network "private_network", ip: "192.168.65.2"

    config.vm.provider :virtualbox do |vb|
        vb.name = "AngularJS"
        vb.customize ["modifyvm", :id, "--memory", "1024"]
    end

    config.vm.provision :shell, path: "bootstrap.sh"
end
